### ISSUE TITLE
example code error

### ISSUE THREAD

**Issue by armstrong13541757** [novitae/igbloks#3]
from igbloks.html import bloks_to_html
import json
from bs4 import BeautifulSoup
file_path = r"C:\Users\Administrator\Downloads\igbloks-main\blocks.json"
with open(file_path, "r") as read: 
    tree = json.load(read)["layout"]["bloks_payload"]["tree"] 
htmled = bloks_to_html(tree)
soup = BeautifulSoup()
dj = soup.find("bk.components.text", {"text": "Date joined"})
dj.parent.find_all("bk.components.text")[-1]["text"]

error
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\igbloks-main\test.py", line 6, in <module>
    tree = json.load(read)["layout"]["bloks_payload"]["tree"]
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

how  to  fix  it ?

**Comment by novitae** [comment]
It comes from the file you're trying to load (`C:\Users\Administrator\Downloads\igbloks-main\blocks.json`). It seems it is not a proper JSON file. Make sure it is.

**Comment by armstrong13541757** [comment]
Hi, Thanks for the fb. I am sure the file is a json file. Can you give me a hand about this error, and It is a big change for me , I can give the file to you by email, and wait for you help.  Please save me. armstrong_guo123@outlook.com

**Comment by armstrong13541757** [comment]
[response.json](https://github.com/novitae/igbloks/files/14645355/response.json)
this is the response file.
Thanks again. You give me the hope.

**Comment by novitae** [comment]
Well this is pretty strange ... I didn't test myself, but it really seems you are not putting the correct path to the file you gave me. A json error like:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
literally says that it tried to read the first character of the file, but that it didn't find anything, so that the file is empty ...

**Comment by armstrong13541757** [comment]
Thanks for the fb, you give me the hope again, the  respone.json from the response of the ins. I want to get some info from the response.  for example , I want get the "input_text_id", the vaule i can not find a way to get it.

**Comment by novitae** [comment]
If only you could read what im telling you ...

**Comment by armstrong13541757** [comment]
Thanks, and I will try again. Thank you for your endurance and lenience.
